CREATE TABLE IF NOT EXISTS `Friends` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `sender_id` INT NOT NULL,
    `receiver_id` INT NOT NULL,
    `status` TINYINT NOT NULL DEFAULT 0,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`),
    FOREIGN KEY(`sender_id`) REFERENCES `Users`(`id`) ON DELETE CASCADE,
    FOREIGN KEY(`receiver_id`) REFERENCES `Users`(`id`) ON DELETE CASCADE
)